// The TypeScript Database writer (src/catalog-model.ts) against legend-lite's own (core's
// CatalogModel.database): for every table of the corpus -- real DuckDB tables, read back through
// the catalog question -- the same Database text, the relation that reads it, conversions, excluded
// columns, or the same refusal, word for word. The corpus is generated by running legend-lite
// (tools/catalogfacts), so any drift between the two fails here.

import assert from 'node:assert/strict';
import { describe, it } from 'node:test';

import { catalogColumnsSql, databaseFromCatalog } from '../src/catalog-model.ts';
import { CATALOG_CORPUS } from './generated/catalog-corpus.ts';

describe('the TypeScript Database writer is legend-lite\'s, case for case', () => {
  it('has a corpus to answer', () => {
    assert.ok(CATALOG_CORPUS.length > 40, `${CATALOG_CORPUS.length} cases`);
  });

  for (const c of CATALOG_CORPUS) {
    it(c.name, () => {
      const table = {
        databaseType: c.input.databaseType,
        path: c.input.path,
        ...(c.input.schema === null ? {} : { schema: c.input.schema }),
        table: c.input.table,
        columns: c.input.columns,
        convertible: c.input.convertible,
      };
      const expected = c.expected;
      if ('error' in expected) {
        assert.throws(() => databaseFromCatalog(table), (e: Error) => {
          assert.equal(e.message, expected.error);
          return true;
        });
        return;
      }
      const db = databaseFromCatalog(table);
      assert.equal(db.text, expected.text);
      assert.deepEqual(JSON.parse(JSON.stringify(db.source)), expected.source);
      assert.deepEqual(db.conversions, expected.conversions);
      assert.deepEqual(db.excluded, expected.excluded);
    });
  }

  it('asks the catalog question with its names as SQL literals', () => {
    const sql = catalogColumnsSql('my s', "o'brien");
    assert.match(sql, /c\.schema_name = 'my s' AND c\.table_name = 'o''brien'/);
    assert.doesNotMatch(sql, /\{schema\}|\{table\}/);
  });
});
