// A query's result type, AS THE COMPILER GIVES IT
// (docs/DATACUBE_TYPED_VALUES_DESIGN_2026_09_27.md, step 1).
//
// Every plane hands DataCube a type in legend-engine's own shapes: the browser
// planner and legend-lite's `pure/v1` answer `lambdaRelationType`'s `RelationType`
// (`{columns: [{name, genericType: {rawType: {fullPath}}}]}`), and a plan carries
// `tdsColumns: [{name, type}]`. Two vocabularies reach this one reader: legend-lite's
// typer says `Integer`, `Decimal`, `DateTime`; legend-engine names a relational column
// with its precise primitive (`meta::pure::precisePrimitives::Varchar`, `Int`,
// `Numeric`, `Timestamp`). Both become the Pure type names the rest of DataCube reads.
// A name it does not know is an ERROR, never a guess: a column typed wrongly
// aggregates wrongly without a word.

import { plainType } from './types.ts';

/** One result column: its name and its Pure type, as the compiler typed it. */
export interface PlanColumn {
  readonly name: string;
  readonly type: string;
}

/** A planned query: the SQL to run, and the type of what it returns. */
export interface Plan {
  readonly sql: string;
  readonly columns: readonly PlanColumn[];
}

/**
 * A type name, in either vocabulary, as the plain Pure type DataCube reads: legend-lite's
 * lattice, generated by running it (`types.ts`); an unknown name is refused.
 */
export function pureType(name: string): string {
  return plainType(name);
}

/** legend-engine's `RelationType` JSON (`lambdaRelationType`'s answer) as columns. */
export function relationColumns(relationType: unknown): PlanColumn[] {
  const columns = (relationType as { columns?: unknown }).columns;
  if (!Array.isArray(columns)) {
    throw new Error('the relation type carries no columns');
  }
  return columns.map((c: unknown) => {
    const col = c as { name?: unknown; genericType?: { rawType?: { fullPath?: unknown } } };
    const path = col.genericType?.rawType?.fullPath;
    if (typeof col.name !== 'string' || typeof path !== 'string') {
      throw new Error(`a relation type column without a name and a type: ${JSON.stringify(c)}`);
    }
    return { name: col.name, type: pureType(path) };
  });
}

/** A plan's `tdsColumns` (generatePlan's `resultType`) as columns. */
export function tdsColumns(plan: unknown): PlanColumn[] {
  const root = (plan as { rootExecutionNode?: { resultType?: { tdsColumns?: unknown } } })
    .rootExecutionNode;
  const cols = root?.resultType?.tdsColumns;
  if (!Array.isArray(cols)) {
    throw new Error('the plan carries no tdsColumns');
  }
  return cols.map((c: unknown) => {
    const col = c as { name?: unknown; type?: unknown };
    if (typeof col.name !== 'string' || typeof col.type !== 'string') {
      throw new Error(`a plan column without a name and a type: ${JSON.stringify(c)}`);
    }
    return { name: col.name, type: pureType(col.type) };
  });
}
